services:
  up:
    image: louislam/uptime-kuma:1
    container_name: up
    restart: always
    volumes:
      - data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.services.kuma.loadbalancer.server.port=3001
    cap_add:
      - NET_RAW # Allow ping
volumes:
  data: null