services:
  mov:
    image: jellyfin/jellyfin
    volumes:
      - config:/config
      - cache:/cache
      - video:/video
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.video.loadbalancer.server.port=8096
    environment:
      - JELLYFIN_PublishedServerUrl=https://DOMAIN.nl # CHANGE ME!
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  config: null
  cache: null
  video: null
