services:
  vintagestory:
    image: pepecitron/vintagestory-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 50200:42420
    volumes:
      - data:/data/server-file
    environment:
      - SERVER_VERSION=1.21.5
volumes:
  data: null